export const START_PROXY = 'START_PROXY';
export const STOP_PROXY = 'STOP_PROXY';

// record table
export const RECORD_TABLE_RECORD_SELECT = 'RECORD_TABLE_RECORD_SELECT';
export const RECORD_TABLE_ADD = 'RECORD_TABLE_ADD';
